import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <nav>
          {/* Prefetched when the link is hovered or enters the viewport */}
          <h1><Link href="/blog">Blog</Link></h1>
          {/* No prefetching */}
          <p></p>
          <h2><Link href="/contact">Contact</Link></h2>
          <p></p>
        </nav>
        {children}
      </body>
    </html>
  );
}
